#!/bin/bash
# Deploy to Railway

echo "🚀 Deploying Claudebot to Railway..."
echo ""
echo "Prerequisites:"
echo "1. Create Railway account at railway.app"
echo "2. Install Railway CLI: npm i -g @railway/cli"
echo "3. Authenticate: railway login"
echo ""
echo "Steps:"
echo "1. git init && git add . && git commit -m 'Initial commit'"
echo "2. railway init"
echo "3. railway service add postgres"
echo "4. Set environment variables:"
echo "   - ANTHROPIC_API_KEY"
echo "   - ELEVENLABS_API_KEY (optional)"
echo "5. railway up"
echo ""
echo "View deployment: railway open"
